site_name: My Docs

theme:
  name: "material"

plugins: 
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - explanation.md
  - reference.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
